name: Update Naukri Profile

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      ALERT_EMAIL_FROM: ${{ secrets.ALERT_EMAIL_FROM }}
      ALERT_EMAIL_TO: ${{ secrets.ALERT_EMAIL_TO }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      HEADLESS: true  # Used by your script to toggle headless mode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run profile updater
        run: python naukri_updater.py
      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: login-screenshots
          path: |
            before_login.png
            login_failed.png
            AfterSave.png
            AfterClickingEdit.png
            BeforeUpdate.png