
name: Update Naukri Profile

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      ALERT_EMAIL_FROM: ${{ secrets.ALERT_EMAIL_FROM }}
      ALERT_EMAIL_TO: ${{ secrets.ALERT_EMAIL_TO }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run profile updater
        run: python naukri_updater.py
